version: '3'

services:
  ais-receiver:
    image: auxority/ais-receiver:latest
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "2001:2001"
    volumes:
      - ./app:/app
    env_file:
      - ./docker/ais-receiver/.env
